### ISSUE TITLE
Can not compile Object.mqh

### ISSUE THREAD

**Issue by renexxxx** [dingmaotu/mql4-lib#3] opened 2017-05-17 07:23 UTC
Getting the following errors: (See attached).
![capture](https://cloud.githubusercontent.com/assets/28289836/26142765/64b6afaa-3b25-11e7-8d08-68e34656ff90.PNG)

**Comment by dingmaotu** [comment] 2017-05-22 03:16
Hi, the usage of Object.mqh has been deprecated. It is removed in the latest commit.

The cause of the error is because MT4 build 1080 released in May 12th, 2017 has several bugs. build 1090 has fixed those bugs. However, do not use this anymore.

**Closed as completed** 2017-05-23 10:26 UTC
Labels: help wanted, wontfix
